### ISSUE TITLE
Missing #define constant

### ISSUE THREAD

**Issue by evandrix** [rofl0r/microwindows#2]
Missing `#define DS_SHELLFONT (DS_SETFONT | DS_FIXEDSYS)` in block
https://github.com/rofl0r/microwindows/blob/ba7fa25096549c46effca6cba29b49e388e244bf/src/include/windlg.h#L25-L39

c.f. https://raw.githubusercontent.com/katahiromz/RisohEditor/9f06ffde35d1a883f086516950db1b48b8512604/data/lib/gcc/i686-w64-mingw32/7.3.0/include/winuser.h

**Comment by rofl0r** [comment]
please use the more up-to-date repo of the original author: https://github.com/ghaerr/microwindows
